modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="notchs_unrealized_ideas_"
version="1.0.0"
displayName="Notch's Unrealized Ideas "
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"

[[dependencies.notchs_unrealized_ideas_]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




